### ISSUE TITLE
https://gmgn.ai/defi/quotation/v1/tokens/kline/sol

### ISSUE THREAD

**Issue by minimalist15** [piotrostr/listen#2]
How does this api actually work ? I keep getting errors trying to use it.

**Comment by piotrostr** [comment]
It does, https://gmgn.ai/defi/quotation/v1/tokens/kline/sol/5cpRQFHLcECN9oBG2hvboWBQM9FMbAD7QdmVgxqcpump?resolution=4h&from=1706719750&to=1721119750 yields 200

**Comment by minimalist15** [comment]
thanks mate!
