### ISSUE TITLE
WSS Connection

### ISSUE THREAD

**Issue by minimalist15** [piotrostr/listen#3]
Hi, 
sorry if this is a stupid question, but i was looking around to understand where to get the api key for the wss but i dont think it is needed? 
how are you using it ? or it was just a suggestion you made?

**Comment by piotrostr** [comment]
For the Solana Mainnet Beta public endpoint you don't need an API key

If you go with a provider there are different methods, e.g. in case of Helius you can authenticate with query params

**Comment by piotrostr** [comment]
https://solana.com/docs/core/clusters

**Comment by minimalist15** [comment]
i was takling about this one sorry : wss://ws.gmgn.ai/stream?_t=true

**Comment by piotrostr** [comment]
Haven't used those streams but it seems that you don't need an API key

<img width="1004" alt="image" src="https://github.com/user-attachments/assets/9e70f590-7bb6-4966-9537-c684f73d5428">

There is an ID param but this appears to be a UUID and it can be specified from the clientside, used for unsubs

**Comment by piotrostr** [comment]
URL is wss://ws.gmgn.ai/stream

**Comment by minimalist15** [comment]
im using it like this : 
import asyncio
import websockets
import json


async def connect_to_websocket():
    uri = "wss://ws.gmgn.ai/stream"
    print(f"Connecting to {uri}")

    async with websockets.connect(uri) as websocket:
        print("Connected to the WebSocket server.")

        try:
            while True:
                print("Waiting to receive a message...")
                message = await websocket.recv()
                process_message(message)
        except websockets.ConnectionClosed:
            print("Connection closed.")
        except Exception as e:
            print(f"An error occurred: {e}")


def process_message(message):
    try:
        data = json.loads(message)
        print(f"Received data: {data}")
        # Add your logic to process the data here
    except json.JSONDecodeError:
        print(f"Received non-JSON message: {message}")


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(connect_to_websocket())

i dont get any response

**Comment by piotrostr** [comment]
> Haven't used those streams but it seems that you don't need an API key
> 
> <img alt="image" width="1004" src="https://private-user-images.githubusercontent.com/63755291/349411514-9e70f590-7bb6-4966-9537-c684f73d5428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDM3NjMsIm5iZiI6MTcyMTIwMzQ2MywicGF0aCI6Ii82Mzc1NTI5MS8zNDk0MTE1MTQtOWU3MGY1OTAtN2JiNi00OTY2LTk1MzctYzY4NGY3M2Q1NDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4MDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYzRkYjRlY2NlMjZlMjY4NzUwNjlhYTJiNjdlYWU4YTI1ZjM0ZDZkN2VhZWE4OGZmMzMyMzUyYzExY2E5NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dWeiCGqBKB62NpdAskDm8R9lMJ6E0qZSWx3jW_Rqvgc">
> There is an ID param but this appears to be a UUID and it can be specified from the clientside, used for unsubs

See the image I sent, try to go to devtools and see the payload you have to send over and the way connection lifecycle is handled

You are going to need to send a subscribe message, then process the incoming messages and send ping messages every here and there and lastly unsubscribe on program exit

In the code snippet you are just connecting, no surprise there is no response :P

**Comment by minimalist15** [comment]
sorry im still a n00b :')

**Comment by piotrostr** [comment]
no worries and good luck!
